name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pem key
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decrypt and use SSH key
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
        INSTANCE: ${{ secrets.INSTANCE }}
        HOST_KEY: ${{ secrets.HOST_KEY }}

      run: |
        openssl aes-256-cbc -d -in archcop.pem.enc -out archcop.pem -k $SECRET_PASSPHRASE -pbkdf2 
        chmod 400 archcop.pem
        # mkdir -p ~/.ssh
        # echo "${HOST_KEY}" > ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no -i archcop.pem ubuntu@$INSTANCE 
        sudo rm -rf testing_aws_automation
        git clone https://github.com/yatharth-gupta/testing_aws_automation.git
        cd testing_aws_automation
        pip install -r req.txt
        sudo systemctl restart githubtesting.service

    # - name: Delete the current REPO
    #   run: |

    # - name: Clone the REPO
    #   run: |

    # - name: Install dependencies
    #   run: |

    # - name: Restart the server
    #   run: |
